name: Execute Alpaca (Paper)

on:
  schedule:
    - cron: "*/20 * * * *"   # every 20 minutes
  workflow_dispatch: {}

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run executor
        env:
          ALPACA_KEY_ID: ${{ secrets.ALPACA_KEY_ID }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_PAPER_BASE_URL: https://paper-api.alpaca.markets
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python executor/alpaca_execute.py
