name: Build Signals
on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build-signals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python research/research.py
      - name: Commit signals
        run: |
          git config user.name "greg-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "update signals [skip ci]" || echo "No changes"
          git push
